### ISSUE TITLE
Function 'Mix_HasMusicDecoder' not found in 'libSDL2_mixer-2.0.so.0'

### ISSUE THREAD

**Issue by Jason23347** [skywind3000/vim-keysound#10]
I was using ubuntu 20.04 with vim version 8.1:
```bash
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 19 2020 13:12:18)
Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
...
+comments          +libcall           -python            +visualextra
+conceal           +linebreak         +python3           +viminfo
...
```

I've already installed python3-sdl2
```bash
sudo apt purge python3-sdl2
sudo apt install python3-sdl2
```

Here's the trace
```
Error detected while processing function <SNR>54_event_vim_enter[2]..<SNR>54_keysound_init[6]..keysound#init[1]..<SNR>97_init[5]..<SNR>97_python:
line    1:
Traceback (most recent call last):
Error detected while processing function <SNR>54_event_vim_enter[2]..<SNR>54_keysound_init[6]..keysound#init[1]..<SNR>97_init[5]..<SNR>97_python:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing function <SNR>54_event_vim_enter[2]..<SNR>54_keysound_init[6]..keysound#init[1]..<SNR>97_init[5]..<SNR>97_python:
line    1:
  File "/home/jason/.vim/bundle/vim-keysound/autoload/keysound.py", line 17, in <module>
Error detected while processing function <SNR>54_event_vim_enter[2]..<SNR>54_keysound_init[6]..keysound#init[1].
.<SNR>97_init[5]..<SNR>97_python:
line    1:
    import sdl2.sdlmixer
Error detected while processing function <SNR>54_event_vim_enter[2]..<SNR>54_keysound_init[6]..keysound#init[1].
.<SNR>97_init[5]..<SNR>97_python:
line    1:
  File "/usr/lib/python3/dist-packages/sdl2/sdlmixer.py", line 149, in <module>
Error detected while processing function <SNR>54_event_vim_enter[2]..<SNR>54_keysound_init[6]..keysound#init[1].
.<SNR>97_init[5]..<SNR>97_python:
line    1:
    Mix_HasMusicDecoder = _bind("Mix_HasMusicDecoder", [c_char_p], SDL_bool)
Error detected while processing function <SNR>54_event_vim_enter[2]..<SNR>54_keysound_init[6]..keysound#init[1].
.<SNR>97_init[5]..<SNR>97_python:
line    1:
  File "/usr/lib/python3/dist-packages/sdl2/dll.py", line 87, in bind_function
Error detected while processing function <SNR>54_event_vim_enter[2]..<SNR>54_keysound_init[6]..keysound#init[1]..<SNR>97_init[5]..<SNR>97_python:
line    1:
    (funcname, self._dll))
Error detected while processing function <SNR>54_event_vim_enter[2]..<SNR>54_keysound_init[6]..keysound#init[1]..<SNR>97_init[5]..<SNR>97_python:
line    1:
ValueError: could not find function 'Mix_HasMusicDecoder' in <CDLL 'libSDL2_mixer-2.0.so.0', handle 55ba56670df0 at 0x7ff6c0f9bf10>
Error detected while processing function <SNR>54_event_vim_enter[2]..<SNR>54_keysound_init[6]..keysound#init[4].
.<SNR>97_python:
line    1:
Traceback (most recent call last):
Error detected while processing function <SNR>54_event_vim_enter[2]..<SNR>54_keysound_init[6]..keysound#init[4].
.<SNR>97_python:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing function <SNR>54_event_vim_enter[2]..<SNR>54_keysound_init[6]..keysound#init[4].
.<SNR>97_python:
line    1:
NameError: name 'keysound' is not defined
```

**Comment by Jason23347** [comment]
It works now after reinstalling `pySDL2`.

**Comment by dfopg** [comment]
> It works now after reinstalling `pySDL2`.

thanks
